-- Add date columns to consumer_pemberkasan for timestamping process steps
ALTER TABLE consumer_pemberkasan
ADD COLUMN IF NOT EXISTS booking_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS slik_ojk_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS proses_berkas_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS ots_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS penginputan_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS analis_data_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS lpa_aprasial_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS pip_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS pk_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS akad_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS pencairan_akad_date TIMESTAMPTZ;
